project_id = "hmwunbhtulrgalqrcnbv"

[functions.search-products]
verify_jwt = false

[functions.store-dashboard]
verify_jwt = true

[functions.razorpay-subscription]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.inventory-assistant]
verify_jwt = true

[functions.inventory-ocr]
verify_jwt = true